version: "3.9"

services:
  e-commerce-backend:
    build: ./e-commerce-backend
    container_name: e-commerce-backend
    ports:
      - "8080:8080"
    environment:
      # JWT settings
      SPRING_APP_JWTSECRET: my-super-secret-key
      SPRING_APP_JWTEXPIRATIONMS: 86400000
      SPRING_PROFILES_ACTIVE: prod
      
      # H2 DB settings
      SPRING_DATASOURCE_URL: jdbc:h2:mem:ecommerce;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      
      # Product image upload path (adjust as needed)
      PRODUCT_IMAGE_UPLOAD_PATH: /usr/local/images
    volumes:
      - backend-images:/usr/local/images


  e-commerce-frontend:
    build: ./e-commerce-frontend
    container_name: e-commerce-frontend
    ports:
      - "4200:80"
    depends_on:
      - e-commerce-backend

volumes:
  backend-images:

